// artifacts/portfolio/src/components/Footer.tsx
import React from 'react';
import { Github, Linkedin, Mail } from 'lucide-react';

export function Footer() {
  const currentYear = new Date().getFullYear();
  
  return (
    <footer className="bg-card border-t border-border py-8">
      <div className="container mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
        
        <p className="text-muted-foreground text-sm font-mono">
          Designed & Built by <span className="text-primary">Abdul-Rahman Sayed</span> &copy; {currentYear}
        </p>

        <div className="flex items-center gap-6">
          <a href="https://github.com/Abdul-RahmanSayed" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary transition-colors">
            <Github className="w-5 h-5" />
          </a>
          <a href="https://linkedin.com/in/abdul-sayed-84643513a/" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary transition-colors">
            <Linkedin className="w-5 h-5" />
          </a>
          <a href="mailto:abdulsayed9@gmail.com" className="text-muted-foreground hover:text-primary transition-colors">
            <Mail className="w-5 h-5" />
          </a>
        </div>
        
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="container">
      <p>
        &copy; For more information come visit my 
        <a href="https://www.linkedin.com/in/abdul-sayed-84643513a/" target="_blank" rel="noopener noreferrer">
          <u>LinkedIn!</u>
        </a>
      </p>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer'
}
</script>

<style scoped>
.footer {
  background-color: var(--color-deep-blue);
  color: white;
  padding: var(--spacing-lg) 0;
  margin-top: auto;
  text-align: center;
}

.footer p {
  margin: 0;
  font-size: var(--font-sm);
}

.footer a {
  color: var(--color-ice-blue);
  transition: color var(--transition-fast);
}

.footer a:hover {
  color: var(--color-coral);
}
</style>
